import { TerminalNode } from './terminalTypes';

export const CBS_TERMINAL_TREE: TerminalNode[] = [
  {
    id: 'savings',
    code: '1',
    labelNe: 'बचत खाता व्यवस्थापन (Savings)',
    labelEn: 'Savings Accounts',
    icon: 'Wallet',
    descriptionNe: 'साधारण, महिला, मुद्दती तथा बाल बचत खाता कारोबार',
    descriptionEn: 'Regular, Women, Fixed Term and Child Savings Schemes',
    children: [
      {
        id: 'regular-savings',
        code: '1',
        labelNe: 'साधारण सदस्य बचत (Regular SAV)',
        labelEn: 'Regular Member Savings (SAV)',
        badge: '६.५% p.a.',
        children: [
          {
            id: 'sav-dep',
            code: '1',
            labelNe: 'नगद जम्मा दाखिला (Cash Deposit)',
            labelEn: 'Cash Deposit',
            operation: 'SAVINGS_DEPOSIT',
          },
          {
            id: 'sav-wth',
            code: '2',
            labelNe: 'नगद भुक्तानी निकाशी (Cash Withdrawal)',
            labelEn: 'Cash Withdrawal',
            operation: 'SAVINGS_WITHDRAWAL',
          },
          {
            id: 'sav-inq',
            code: '3',
            labelNe: 'खाता मौज्दात सोधपुछ (Balance Inquiry)',
            labelEn: 'Balance Inquiry',
            operation: 'SAVINGS_BALANCE_INQUIRY',
          },
        ],
      },
      {
        id: 'women-savings',
        code: '2',
        labelNe: 'नारी उत्थान महिला बचत (Women Group)',
        labelEn: 'Nari Utthan Women Savings',
        badge: '८.५% p.a.',
        children: [
          {
            id: 'women-dep',
            code: '1',
            labelNe: 'नगद जम्मा दाखिला (Cash Deposit)',
            labelEn: 'Cash Deposit',
            operation: 'SAVINGS_DEPOSIT',
          },
          {
            id: 'women-wth',
            code: '2',
            labelNe: 'नगद भुक्तानी निकाशी (Cash Withdrawal)',
            labelEn: 'Cash Withdrawal',
            operation: 'SAVINGS_WITHDRAWAL',
          },
        ],
      },
      {
        id: 'term-deposit',
        code: '3',
        labelNe: 'मुद्दती निक्षेप प्रमाणपत्र (Fixed Deposit Mudhati)',
        labelEn: 'Term Deposit (Mudhati)',
        badge: '११.०% p.a.',
        children: [
          {
            id: 'fd-book',
            code: '1',
            labelNe: 'नयाँ मुद्दती दाखिला (Create Term Deposit)',
            labelEn: 'Create Term Deposit',
            operation: 'SAVINGS_DEPOSIT',
          },
          {
            id: 'fd-inq',
            code: '2',
            labelNe: 'मुद्दती परिपक्वता तथा विवरण (FD Status)',
            labelEn: 'Term Deposit Status',
            operation: 'SAVINGS_BALANCE_INQUIRY',
          },
        ],
      },
      {
        id: 'child-savings',
        code: '4',
        labelNe: 'बाल शिक्षा भविष्य बचत (Child Savings)',
        labelEn: 'Child Education Savings',
        badge: '९.०% p.a.',
        children: [
          {
            id: 'child-dep',
            code: '1',
            labelNe: 'नगद जम्मा दाखिला (Cash Deposit)',
            labelEn: 'Cash Deposit',
            operation: 'SAVINGS_DEPOSIT',
          },
          {
            id: 'child-wth',
            code: '2',
            labelNe: 'नगद भुक्तानी निकाशी (Cash Withdrawal)',
            labelEn: 'Cash Withdrawal',
            operation: 'SAVINGS_WITHDRAWAL',
          },
        ],
      },
    ],
  },
  {
    id: 'loans',
    code: '2',
    labelNe: 'ऋण तथा किस्ता व्यवस्थापन (Loans)',
    labelEn: 'Loan & EMI Management',
    icon: 'BadgePercent',
    descriptionNe: 'कृषि, व्यापार, आपतकालीन तथा मुद्दती धितो कर्जा किस्ता',
    descriptionEn: 'Agro, SME Business, Micro and Collateral Loan Portfolios',
    children: [
      {
        id: 'agro-loan',
        code: '1',
        labelNe: 'कृषि तथा पशुधन कर्जा (Agro Loan)',
        labelEn: 'Agriculture & Livestock Loan',
        badge: '८.५% Diminishing',
        children: [
          {
            id: 'agro-emi',
            code: '1',
            labelNe: 'किस्ता भुक्तानी संकलन (Collect EMI)',
            labelEn: 'Collect EMI Payment',
            operation: 'LOAN_EMI_PAYMENT',
          },
          {
            id: 'agro-settle',
            code: '2',
            labelNe: 'अग्रिम पूर्ण राफसाफ (Full Foreclosure)',
            labelEn: 'Full Foreclosure Settlement',
            operation: 'LOAN_FULL_SETTLEMENT',
          },
          {
            id: 'agro-inq',
            code: '3',
            labelNe: 'किस्ता तालिका तथा बाँकी साँवा (Loan Schedule)',
            labelEn: 'Loan Amortization Inquiry',
            operation: 'LOAN_SCHEDULE_INQUIRY',
          },
        ],
      },
      {
        id: 'sme-loan',
        code: '2',
        labelNe: 'साना तथा मझौला उद्यम कर्जा (SME Business)',
        labelEn: 'Small Business & SME Loan',
        badge: '१२.०% p.a.',
        children: [
          {
            id: 'sme-emi',
            code: '1',
            labelNe: 'किस्ता भुक्तानी संकलन (Collect EMI)',
            labelEn: 'Collect EMI Payment',
            operation: 'LOAN_EMI_PAYMENT',
          },
          {
            id: 'sme-settle',
            code: '2',
            labelNe: 'अग्रिम पूर्ण राफसाफ (Full Foreclosure)',
            labelEn: 'Full Foreclosure Settlement',
            operation: 'LOAN_FULL_SETTLEMENT',
          },
        ],
      },
      {
        id: 'fd-margin-loan',
        code: '3',
        labelNe: 'मुद्दती निक्षेप धितो कर्जा (९०% Instant Margin)',
        labelEn: 'Loan Against FD Certificate',
        badge: '१.५% Spread',
        children: [
          {
            id: 'fd-margin-emi',
            code: '1',
            labelNe: 'किस्ता वा ब्याज दाखिला (Pay Interest/EMI)',
            labelEn: 'Pay Loan Interest / EMI',
            operation: 'LOAN_EMI_PAYMENT',
          },
        ],
      },
    ],
  },
  {
    id: 'shares',
    code: '3',
    labelNe: 'सेयर पुँजी व्यवस्थापन (Share Capital)',
    labelEn: 'Share Capital & Certificates',
    icon: 'Award',
    descriptionNe: 'सेयर कित्ता खरिद, प्रमाणपत्र प्रिन्ट र लाभांश अभिलेख',
    descriptionEn: 'Share Units Issuance, Member Equity and Certificates',
    children: [
      {
        id: 'equity-issuance',
        code: '1',
        labelNe: 'साधारण सेयर कित्ता बाँडफाँट (Equity Issuance)',
        labelEn: 'Ordinary Share Allocation',
        badge: 'रु. १००/कित्ता',
        children: [
          {
            id: 'share-purchase-post',
            code: '1',
            labelNe: 'नयाँ सेयर खरिद दाखिला (Post Share Purchase)',
            labelEn: 'Post Share Purchase',
            operation: 'SHARE_PURCHASE',
          },
          {
            id: 'share-certificate-inq',
            code: '2',
            labelNe: 'सेयर प्रमाणपत्र अभिलेख (Certificate Inquiry)',
            labelEn: 'Share Certificate Record',
            operation: 'SHARE_CERTIFICATE_INQUIRY',
          },
        ],
      },
    ],
  },
  {
    id: 'teller',
    code: '4',
    labelNe: 'काउन्टर तथा दैनिक नगद (Teller Desk)',
    labelEn: 'Teller Cash & Daily Collection',
    icon: 'Calculator',
    descriptionNe: 'काउन्टर नगद गन्ती, भल्ट मिलान तथा दैनिक बन्द',
    descriptionEn: 'Drawer Cash Denominations, Vault Handover and Batch Posting',
    children: [
      {
        id: 'cash-drawer-desk',
        code: '1',
        labelNe: 'दैनिक काउन्टर नगद मिलान (Cash Reconciliation)',
        labelEn: 'Daily Cash Reconciliation',
        children: [
          {
            id: 'denom-count',
            code: '1',
            labelNe: 'भौतिक नोट गन्ती प्रविष्टि (Denomination Entry)',
            labelEn: 'Denomination Entry',
            operation: 'TELLER_DENOMINATION_ENTRY',
          },
          {
            id: 'vault-handover',
            code: '2',
            labelNe: 'काउन्टर भल्ट बन्द (Close Drawer to Vault)',
            labelEn: 'Close Drawer to Vault',
            operation: 'TELLER_DRAWER_RECONCILE',
          },
        ],
      },
    ],
  },
];
